version: "3"
services:
  web:
    image: alpine-nginx:99
    volumes:
       - "../src:/src:rw"
       - "./site.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
  php:
    image: php7.2-composer-pdo:1.1
    volumes:
      - "../src:/src:rw"
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
#MySQL database username
      - MYSQL_USER=username
#MySQL database password
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "../database:/var/lib/mysql:rw"
